### ISSUE TITLE
Github workflow for auto building and deploying of the website. 

### ISSUE THREAD

**Issue by LordShenron** [ProjectSakura/download#21]
@ArunTeltia add gssoc labels

**Comment by ArunTeltia** [comment]
Added

**Comment by mis-coder** [comment]
hi! can I work on this issue?

**Comment by LordShenron** [comment]
> hi! can I work on this issue?

It's assigned to you.

**Comment by mis-coder** [comment]
Is this website deployed anywhere yet?

**Comment by mis-coder** [comment]
> Is this website deployed anywhere yet?

if yes please provide the link here

**Comment by LordShenron** [comment]
> Is this website deployed anywhere yet?

this is deployed on github pages.. see gh-pages branch. After building the website we need to push the built site to gh-pages branch. 

check: https://projectsakura.xyz/download

**Comment by mis-coder** [comment]
> > Is this website deployed anywhere yet?
> 
> this is deployed on github pages.. see gh-pages branch. After building the website we need to push the built site to gh-pages branch.
> 
> check: https://projectsakura.xyz/download

Okay got it

**Comment by ArunTeltia** [comment]
Pretty sure we need to add husky for react app and add some pre push and pre commit script
Not sure what we use for vue tho @mis-coder  If you have problems please let me know 

We will work on some other issue for you to work on

**Comment by mis-coder** [comment]
> Pretty sure we need to add husky for react app and add some pre push and pre commit script
> Not sure what we use for vue tho @mis-coder If you have problems please let me know
> 
> We will work on some other issue for you to work on

Okay

**Comment by mis-coder** [comment]
hi, i need github username and email to add in .yml file

**Comment by LordShenron** [comment]
> hi, i need github username and email to add in .yml file

Username: LordShenron
Email: shen.priyanshu@gmail.com

**Comment by mis-coder** [comment]
hi i have created pr, kindly check it and let me know if there is any problem

**Comment by LordShenron** [comment]
Completed with: https://github.com/ProjectSakura/download/commit/ffd70ea2f72d59eacdecc957a98f0004af2d1b98
